# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_google_connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_response',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
