# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=10)),
                ('bot_response', models.CharField(max_length=1000)),
                ('source_data', models.CharField(max_length=1000)),
            ],
        ),
    ]
